### ISSUE TITLE
📌 Todo list & known issues

### ISSUE THREAD

**Issue by cp2004** [cp2004/OctoPrint-CameraStreamer-Control#1]
I'll try and keep track of the things I know are not implemented or broken in the plugin, so you know if you run into them

## TODOs

* [ ] Smoother settings UI
* [ ] Timeout if webrtc hangs in loading

## Known issues

* [ ] Can't unload mjpg streams on safari, so work around
* [ ] Reloads stream on every settings change

## Future features

* [ ] Static snapshot stream type
* [ ] HLS stream type
